api_key: 45482d483134a0ad21868cafb32ef367-us2
cron: false
batch_limit: 100
api_classname: Mailchimp\Mailchimp
test_mode: false
_core:
  default_config_hash: x8k6uOqmSHPqpp71jYGxHF3_SAs3U-Pha3YCntQIhPU

